services:
  graphql:
    build: services/graphql
    container_name: graphql
    ports:
      - "5000:5000"
    volumes:
      - ./services/graphql/app:/usr/src/app
      - ./services/graphql/package.json:/usr/src/app/package.json
      - ./services/graphql/package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  sensor:
    build: services/sensor
    container_name: sensor
    volumes:
      - ./data:/data
    depends_on:
      - mongodb
    environment:
      - TZ=UTC
      - MONGODB_URI=mongodb://mongodb:27017/sensordata
    networks:
      - sensors-network

  mongodb:
    build: services/mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sensordata
    volumes:
      - mongodb_data:/data/db
    networks:
      - sensors-network

  dashboard:
    build: services/dashboard
    container_name: dashboard
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sensordata
      - NODE_ENV=production
    depends_on:
      - mongodb
    volumes:
      - ./services/dashboard/app:/usr/src/app
      - ./services/graphql/package.json:/usr/src/app/package.json
      - ./services/graphql/package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  sensors-network:
    driver: bridge

volumes:
  mongodb_data: