@startuml
!theme plain

title "Services architecture"

' Custom styling
skinparam {
    BorderThickness 2
    TitleBorderRoundCorner 15
    Padding 5
    backgroundColor white
    defaultFontName Arial
    ArrowColor #666666
    componentStyle rectangle
}

' Components
component "Python Sensor\nSimulator" as sensor #918EF4
queue "Apache Kafka" as kafka #6F9CEB
component "Node Express Server\nGraphQL API" as server #306BAC
database "MongoDB" as mongodb #30409C
component "Client Applications" as client #98B9F2

' Relations
sensor -down-> kafka
kafka -down-> server
server -down-> mongodb
mongodb -up-> server
server -left-> client
client -right-> server

legend right
    Legend:
    |= Component                      |= Type             |
    |<#918EF4> Sensor                 | Data Source       |
    |<#6F9CEB> Kafka                  | Message Broker    |
    |<#98B9F2> Dashboard              | Frontend          |
    |<#306BAC> Express Server/GraphQL | API Services      |
    |<#30409C> MongoDB                | Database          |
endlegend

@enduml