FROM apache/kafka:latest

WORKDIR /opt/kafka/bin/

# RUN bash kafka-topics.sh --create --topic measurements --bootstrap-server localhost:9092
# RUN bash kafka-topics.sh --describe --topic measurements --bootstrap-server localhost:9092

# bash kafka-console-producer.sh --topic measurements --bootstrap-server localhost:9092
# bash kafka-console-consumer.sh --topic measurements --from-beginning --bootstrap-server localhost:9092